development:
  db:
    name: 'blog.db'
    adapter: 'sqlite'
    connection_line: 'sqlite:/'
    path: './temp/test_blog.db'
test:
  db:
    name: 'blog.db'
    adapter: 'sqlite'
    connection_line: 'sqlite:/'
    path: './temp/test_blog.db'
